<#
    Deletes the starter-kit authentication and settings UI.

    Those screens import Wayfinder route helpers (@/routes/profile,
    @/routes/security, @/routes/appearance) that no longer exist now that
    Fortify's routes are switched off — so Vite fails to resolve them and the
    dev overlay covers every page.

    This project keeps exactly one privileged surface: the PIN-gated /admin.

    Usage (from the project root):
        powershell -ExecutionPolicy Bypass -File .\remove-auth-ui.ps1

    Add -WhatIf to see what it would remove without touching anything.
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param()

$root = $PSScriptRoot
$js = Join-Path $root 'resources\js'

# Pages and layouts for the removed login / dashboard / settings surface.
$paths = @(
    'pages\auth',
    'pages\settings',
    'pages\dashboard.tsx',
    'pages\welcome.tsx',
    'layouts\app-layout.tsx',
    'layouts\app',
    'layouts\auth-layout.tsx',
    'layouts\auth',
    'layouts\settings',

    # Components only those screens used.
    'components\app-sidebar.tsx',
    'components\app-sidebar-header.tsx',
    'components\app-header.tsx',
    'components\app-logo.tsx',
    'components\app-logo-icon.tsx',
    'components\nav-main.tsx',
    'components\nav-footer.tsx',
    'components\nav-user.tsx',
    'components\user-info.tsx',
    'components\user-menu-content.tsx',
    'components\breadcrumbs.tsx',
    'components\delete-user.tsx',
    'components\appearance-tabs.tsx',
    'components\password-input.tsx',
    'components\manage-passkeys.tsx',
    'components\manage-two-factor.tsx',
    'components\passkey-item.tsx',
    'components\passkey-register.tsx',
    'components\passkey-verify.tsx'
)

# Kept on purpose: components\app-shell.tsx, components\app-content.tsx,
# components\ui\*, components\input-error.tsx, hooks\*, lib\*, types\* —
# the portfolio and the admin still use them.

Write-Host ''
Write-Host 'Removing the starter-kit auth / settings UI' -ForegroundColor Cyan
Write-Host ''

$removed = 0
$skipped = 0

foreach ($relative in $paths) {
    $full = Join-Path $js $relative

    if (-not (Test-Path $full)) {
        $skipped++
        continue
    }

    if ($PSCmdlet.ShouldProcess($full, 'Remove')) {
        Remove-Item $full -Recurse -Force
        Write-Host "  removed  resources\js\$relative" -ForegroundColor DarkGray
        $removed++
    }
}

Write-Host ''
Write-Host "Removed $removed, already absent $skipped." -ForegroundColor Green

# Wayfinder rewrites these on the next dev/build run; clearing them drops any
# helper for a route that no longer exists.
foreach ($generated in @('routes', 'actions', 'wayfinder')) {
    $full = Join-Path $js $generated

    if ((Test-Path $full) -and $PSCmdlet.ShouldProcess($full, 'Remove (regenerated by Wayfinder)')) {
        Remove-Item $full -Recurse -Force
        Write-Host "  cleared  resources\js\$generated (Wayfinder regenerates it)" -ForegroundColor DarkGray
    }
}

Write-Host ''
Write-Host 'Now run:' -ForegroundColor Cyan
Write-Host '  php artisan optimize:clear'
Write-Host '  php artisan cache:clear'
Write-Host '  npm run build'
Write-Host ''
Write-Host 'Then restart composer dev if it is running.' -ForegroundColor DarkGray
Write-Host ''
